# Generated by Django 3.0.7 on 2020-09-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='button_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='feature',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
