# Generated by Django 3.0.7 on 2020-09-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200915_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='feature',
        ),
        migrations.AlterField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='feature',
            field=models.ManyToManyField(to='payment.Feature'),
        ),
    ]
