# Generated by Django 3.0.7 on 2020-09-12 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='active',
            new_name='status',
        ),
        migrations.AddField(
            model_name='header',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='position',
            field=models.CharField(choices=[('F', 'Firts'), ('S', 'Second'), ('T', 'Third')], max_length=1, unique=True),
        ),
    ]
