# Generated by Django 3.0.7 on 2020-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200912_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='position',
            field=models.CharField(blank=True, choices=[('F', 'Firts'), ('S', 'Second'), ('T', 'Third')], max_length=1, null=True, unique=True),
        ),
    ]
