# Generated by Django 3.0.7 on 2020-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200912_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
